config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "pages#home"

  resources :projects

  resources :my_bugs do
    member do
     post :bug_status
    end
  end

end

app/models/my_bug.rb
class MyBug < ApplicationRecord

	validates :title, presence: true
  	validates :description, presence: true
  	validates :bug_type, presence: true
  	validates :status, presence: true
  	validates :user_id, presence: true
  	validates :project_id, presence: true
  	validates :deadline, presence: true

  	mount_uploader :image, AvatarUploader
  	
  	belongs_to :user
  	belongs_to :project
end

app/controllers/my_bugs_controller.rb
class MyBugsController < ApplicationController

	def index
		flash[:danger] = "Bugs have no existance without project"
		redirect_to projects_path
		# if can? :read, MyBug
		# 	if manager? || qa?
		# 		@bugs = MyBug.where(user_id: current_user.id)
		# 	else
		# 		# @bugs = current_user.my_bugs
		# 		@bugs = MyBug.where(assigned_to: current_user.id )
		# 	end
		# else

		# 		flash[:danger] = "Please login to use our app"
		# 		redirect_to request.referer
		# end
	end

	def new
		if can? :create, MyBug
			@project_id = params[:project_id]
			if @project_id.present?
				if can_create_bug(params[:project_id])
					@bug = MyBug.new
				else
					flash[:danger] = "Access Denied..."
					redirect_to root_path
				end
			else
				flash[:danger] = "Can't create bug without a project"
				redirect_to projects_path
			end
		else
			flash[:danger] = "Only Manager or Qa can create bug"
			redirect_to root_path
		end
	end

	def create
		if can? :create, MyBug
			@bug = MyBug.new(bug_params)
			# @bug.bug_type = params[:my_bug][:bug_type]

			if @bug.save
				redirect_to project_path(@bug.project_id)
			else
				flash[:danger] = "Request failed.."
				render 'new'
			end
		else
			flash[:danger] = "Only Manager or Qa can create bug"
		end
	end

	def show
		if can? :read, MyBug
			@bug = MyBug.find(params[:id])
			if !can_update_bug(@bug.project_id)
				flash[:dnager] = "Access Denied..."
				redirect_to root_path
			end
		else
			flash[:danger] = "Access Denied..."
			redirect_to request.referer
		end
	end

	def edit
		if !can_update_bug(@bug.project.id)
			@bug = MyBug.find(params[:id])
			flash[:danger] = "Only Project Related Person can Make changes"
			redirect_to root_path
		end
	end

	def update
		@bug = MyBug.find(params[:id])
		if @bug.update(bug_params)
			flash[:success] = "Updated Sucessfully"
		else
			flash[:danger] = "Update failed.. try again later.."
		end
		redirect_to my_bug_path(@bug)
	end

	def bug_status
		@bug = MyBug.find(params[:id])
		@bug.update(status: params[:status])
		render json: {success: "ok"}
	end

	def destroy
		if can_update_bug(@bug.project.id)
			if can? :destroy, MyBug
				@bug = MyBug.find(params[:id])
				if @bug.destroy
					flash[:success] = "Deleted Sucessfully..."
					redirect_to my_bugs_path
				else
					flash[:danger] = "Something went wrong..."
					render 'my_bug'
				end
			else
				flash[:danger] = "Only Creater of bug can delete his bug..."
				render 'my_bug'
			end
		end
	end

	private

	def bug_params
		params.require(:my_bug).permit(:title,:description,:assigned_to,:status,:bug_type,:project_id,:user_id,:status,:deadline,:image)
	end

end

app/views/my_bugs/edit.html.erb
<div class=" d-flex flex-column align-items-center my-4">

  <h2>Update Bug</h2>

  <%= form_for @bug do |f| %>

    <div class="form-group">
      <%= f.label :title %><br />
      <%= f.text_field :title, class: "form-control my-1" , autofocus: true, placeholder: "Enter Bud's Title" , required: true %>
    </div>

    <div class="form-group">
      <%= f.label :description %><br />
      <%= f.text_field :description , class: "form-control my-1" , autofocus: true, placeholder: "Enter Bug's description", required: true %>
    </div>

    <div class="field">
      <%= f.hidden_field :project_id, value: @bug.project_id %>
    </div>


    <!-- ========================================================= -->
    <div class="form-group">
      <% bug_status = [['New', 'new'],['Started','started']] %>
      <% if @bug.bug_type == 'bug' %>
        <% bug_status.push(['Resolved','resolved']) %>
      <% else %>
        <% bug_status.push(['Completed'],['Completed']) %>
      <% end %>
      <%= f.label :status %><br />
      <%= f.select(:status, options_for_select(bug_status), {}, {:class => 'form-control form-control my-1', required: true})  %>
    </div>

    <div>
      <%= f.label :assigned_to, "Developers to assign" %><br />
      <% developers = Project.find(@bug.project_id).users %>
      <% result = developers.select do |elem| %>
          <% elem.user_type == "developer" %>
      <% end %>
      <%= f.collection_select :assigned_to, result, :id , :name , {} , {multiple: false, required: true , class: 'form-control form-control my-1' } %>
    </div>

    <div class="field">
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>

    <div class="form-group">
      <%= f.label :bug_type %><br />
      <%= f.select(:bug_type, options_for_select([['Bug', 'bug'], ['Feature', 'feature']] ), {}, {:class => 'form-control form-control my-1', required: true})  %>
    </div>

    <div class="form-group">
      <%= f.label :deadline %><br />
      <%= f.date_select :deadline, start_year: Time.now.year, end_year: Time.now.year + 10 , :html=>{:class => "form-control form-control my-1", required: true} %>
    </div>

    <div class="actions">
      <%= f.file_field :image, accept: 'image/png,image/jpeg' , class:"my-1 btn btn-primary col-12"%>
    </div>

    <div class="actions">
      <%= f.submit "Update" , class:"my-1 btn btn-primary col-12"%>
    </div>
  <% end %>
</div>

app/views/my_bugs/index.html.erb
<%= render 'shared/bug_listing' , bug: @bugs %>

app/views/my_bugs/new.html.erb
<div class=" d-flex flex-column align-items-center my-4">

  <h2>Create new Bug</h2>

  <%= form_for @bug do |f| %>

    <div class="form-group">
      <%= f.label :title %><br />
      <%= f.text_field :title, class: "form-control my-1" , autofocus: true, placeholder: "Enter Bud's Title" %>
    </div>

    <div class="form-group">
      <%= f.label :description %><br />
      <%= f.text_field :description , class: "form-control my-1" , autofocus: true, placeholder: "Enter Bug's description" %>
    </div>

    <div class="field">
      <%= f.hidden_field :project_id, value: @project_id %>
    </div>

    <div class="field">
      <%= f.hidden_field :status, value: "new" %>
    </div>

    <div>
      <%= f.label :assigned_to, "Developers to assign" %><br />
      <% developers = Project.find(@project_id).users %>
      <% result = developers.select do |elem| %>
          <% elem.user_type == "developer" %>
      <% end %>
      <%= f.collection_select :assigned_to, result, :id , :name , {} , {multiple: false, required: true , class: 'form-control form-control my-1' } %>
    </div>

    <div class="field">
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>

    <div class="form-group">
      <%= f.label :bug_type %><br />
      <%= f.select(:bug_type, options_for_select([['Bug', 'bug'], ['Feature', 'feature']] ), {}, {:class => 'form-control form-control my-1'})  %>
    </div>

    <div class="form-group">
      <%= f.label :deadline %><br />
      <%= f.date_select :deadline, start_year: Time.now.year, end_year: Time.now.year + 10 , :html=>{:class => "form-control form-control my-1"} %>
    </div>

    <div class="actions">
      <%= f.file_field :image, accept: 'image/png,image/gif' , class:"my-1 btn btn-primary col-12"%>
    </div>

    <div class="actions">
      <%= f.submit "Create" , class:"my-1 btn btn-primary col-12"%>
    </div>
  <% end %>
</div>

app/views/my_bugs/show.html.erb
<div class="d-flex flex-column align-items-center">
	<br>
	<h1>Details</h1>
	<br>
	<div class="col-md-10">
		<div class="h-100 p-5 text-white bg-dark rounded-3 d-flex align-items-center justify-content-around">
			<% if @bug.image.present? %>
			<div>
				<%= image_tag @bug.image.url, style: 'height:150px;width:150px;' , class: "col-md-2" %>
			</div>
			<% end %>
			<div class="col-md-8">
				<h2>Title : <%= @bug.title.capitalize %></h2>
				<hr>
				<p>Description : <%= @bug.description.capitalize %> </p>
				<br>
				<hr>
				<div class="d-flex justify-content-between">
					<small>Created by : <%= @bug.user.name.capitalize %></small>
					<% if @bug.assigned_to.present? %>
					<% if @bug.assigned_to == current_user.id %>
					<div id="bug-status">
						<% bug_status = [['New','new'],['Started','started']] %>
						<% if @bug.bug_type == 'bug' %>
							<% bug_status.push(['Resolved','resolved']) %>
						<% else %>
							<% bug_status.push(['Completed','completed']) %>
						<% end %>
						<label for="bugselect">Status : </label>
						<select id="bugselect">
							<% bug_status.each do |b| %>
								<option <%= 'selected' if b[1] == @bug.status %> value=<%= b[1] %>><%= b[0] %></option>
							<% end %>
						</select>
					</div>
					<% else %>
					<div>
						<small>Status : <%= @bug.status %></small>
					</div>
					<% end %>

					<small>Assigned to : <%= User.find(@bug.assigned_to).name.capitalize %> </small>
					<% end %>
				</div>
				<hr>
				<div class="d-flex justify-content-center">
					<%= link_to "Return", :back , class: "btn btn-primary mx-3" %>

					<%= link_to "Project Details", project_path(Project.find(@bug.project_id)) , class: "btn btn-warning mx-3" %>
					<% if can_update_bug(@bug.project_id) %>
					<%= link_to "Edit Bug", edit_my_bug_path(@bug) , class: "btn btn-warning mx-3" %>
					<%= link_to "Delete Bug", my_bug_path(@bug), method: :delete , data: {confirm: "Are you sure?"} , class: "btn btn-danger mx-3" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
$(document).on('change', '#bugselect', function() {
  // alert("Hello");
  var url = "/my_bugs/" + <%= @bug.id %> + "/bug_status"
  console.log("URl", url);
  $.ajax({
    type: "POST",
    url: url,
    dataType: 'json',
    data: {
    	"status" : $("#bugselect").val()
    },
    success: function(data) {
      alert('Bug status changed to : ' + $("#bugselect").val());
    },
    error: function(e){
      alert('error');
    }
  })
});
</script>