config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "pages#home"

  resources :projects

  resources :my_bugs do
    member do
     post :bug_status
    end
  end

end

app/views/shared/_bug_listing.html.erb
<div class="d-flex flex-column align-items-center">
	<h1 class="mt-5">
		<%= title %>
	</h1>
	<% bug.each do |b| %>
	<div class="col-md-11 my-3">
		<div class="h-100 p-5 text-white bg-dark rounded-3 d-flex align-items-center justify-content-around">
			<% if b.image.present? %>
			<div class: "col-md-1" >
				<%= image_tag b.image.url, style: 'height:150px;width:150px;' %>
			</div>
			<% end %>
			<div class="col-md-8">
				<h2><%= link_to "Title : #{b.title.capitalize}" , my_bug_path(b), style: "text-decoration:none" %></h2>
				<hr>
				<p>Description : <%= b.description.capitalize.truncate(100) %> </p>
				<br>
				<div class="d-flex justify-content-between">
					<span>Type : <%= b.bug_type.capitalize %></span>
					<span>Status : <%= b.status.capitalize %> </span>
				</div>
				<hr>
				<div class="d-flex justify-content-between">
					<small>Created by : <%= b.user.name.capitalize %></small>
					<% if b.assigned_to.present? %>
					<small>Assigned to : <%= User.find(b.assigned_to).name.capitalize %> </small>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/shared/_flash.html.erb
<div class="container my-3">
	<% flash.each do |name,msg| %>
	<div class="alert alert-<%= if name == "notice" then 'success' else name end %>" role="alert">
	        <%= msg %>
	</div>
	<% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Bug'ies", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home" , root_path , class: "nav-link active" %>
        </li>
        
        <% if manager? %>
        <li class="nav-item">
          <li><%= link_to "New Project", new_project_path , class: "nav-link"%>
        </li>
        <% end %>

      </ul>
      <form class="d-flex">
          <% if user_signed_in? %>

          <div class="collapse navbar-collapse mx-5" id="navbarNavDarkDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= current_user.name %>
                  <% if current_user.user_type == "manager" %>
                  Manager
                  <% elsif current_user.user_type == "qa" %>
                  Qa
                  <% else %>
                  Developer
                  <% end %>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                  <li><%= link_to "Edit Profile", edit_user_registration_path , class: "dropdown-item"%></li>
                  </li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete , class: "dropdown-item"%></li>
                </ul>
              </li>
            </ul>
          </div>
        
        
          
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path , class: "nav-link text-dark"%>
            <%= link_to "Sign In", new_user_session_path, class: "nav-link text-dark"%>
          <% end %>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_projects_listing.html.erb
<div class="d-flex flex-column align-items-center">
<h1>
	Projects
</h1>

<% obj.each do |p| %>

 <div class="col-md-8 my-2">
	<div class="h-100 p-5 text-white bg-dark rounded-3">
	    <h2><%= link_to "#{p.name}", project_path(p) %></h2>
	    <p><%= p.description.truncate(75) %></p>
	    <div class="d-flex justify-content-between">
	    	<small>Created by: <%=p.user.name %></small><small>Created at: <%=  time_ago_in_words(p.created_at) %></small>
	    </div>
	</div>
</div>

<% end %>
</div>