config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "pages#home"

  resources :projects

  resources :my_bugs do
    member do
     post :bug_status
    end
  end

end

app/models/project.rb
class Project < ApplicationRecord
	validates :name, presence: true
  	validates :description, presence: true
  	validates :user_id, presence: true

  	has_many :my_bugs , dependent: :destroy

  	belongs_to :user
  	has_many :users_projects
  	has_many :users, through: :users_projects
  	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def new
		if can? :create , Project
			@project = Project.new
			@dev = User.where(user_type: "developer")
			@qa = User.where(user_type: "qa")
		else
			flash[:danger] = "Only manager can create project"
			redirect_to root_path
		end
		# if manager?
		# 	@users1 = User.where(user_type: "developer")
		# 	@users2 = User.where(user_type: "qa")
		# 	@project = Project.new
		# else
		# 	flash[:danger] = "Only manager can create project"
		# 	redirect_to root_path
		# end
	end

	def create
		if can? :create, Project
			# debugger
			@project = Project.new(project_params)
			@project.user_id = current_user.id

			if @project.save
				redirect_to project_path(@project)
			else
				flash[:danger] = "Failed"
				redirect_to new_project_path
			end
		else
			flash[:danger] = "Only manager can create project"
			redirect_to root_path
		end
		
	end

	def show
		@project = Project.find(params[:id])
		if !can_update_bug(@project.id)
			flash[:danger] = "Access Denied"
			redirect_to projects_path
		end
	end

	def edit
		@project = Project.find(params[:id])
		unless can? :update, @project
			flash[:danger] = "Only manager and creater can edit project"
			redirect_to root_path
		end
		
	end

	def update

		if can? :update, Project
			@project = Project.find(params[:id])
			if @project.update(project_params)
				redirect_to project_path(@project)
			else
				flash[:danger] = "Something went wrong! Try again later!"
				render 'edit'
			end
		else
			flash[:danger] = "Only manager and creater can update projects"
			redirect_to projects_path
		end

	end

	def destroy
		@project = Project.find(params[:id])
		if can? :destroy, Project
			if Project.find(params[:id]).destroy
				flash[:success] = "Deleted Sucessfully"
				redirect_to projects_path
			else
				flash[:danger] = "Something went Wrong. Try Later!"
			end
		else
			flash[:danger] = "Only manager can delete project"
			redirect_to projects_path
		end
	end

	def index
		if current_user.user_type == 'manager'
			@projects = Project.where(user_id: current_user.id)
		else
			@projects = current_user.projects
		end
	end

	private

		def project_params
			params.require(:project).permit(:name,:description,user_ids: [])
		end

end

app/views/projects/edit.html.erb
<div class=" d-flex flex-column align-items-center my-4">

  <h2>Edit Project</h2>

  <%= form_for @project do |f| %>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class: "form-control my-1" , autofocus: true, placeholder: "Enter Project name" , required: true %>
    </div>

    <div class="form-group">
      <%= f.label :description %><br />
      <%= f.text_field :description , class: "form-control my-1" , autofocus: true, placeholder: "Enter Project description" , required: true %>
    </div>
    
    <div>
      <%= f.label :user_ids, "Developers" %><br />
      <%= f.collection_select :user_ids, User.where(user_type: "developer"), :id , :name , {} , {multiple: true, required: true, class: 'form-control form-control my-1' } %>
    </div>
    <div>
      <%= f.label :user_ids, "QAs" %><br />
      <%= f.collection_select :user_ids, User.where(user_type: "qa"), :id , :name , {} , {multiple: true, required: true, class: 'form-control form-control my-1' } %>
    </div>

    <div class="actions">
      <%= f.submit "Update Project" , class:"my-1 btn btn-primary col-12"%>
    </div>
  <% end %>
</div>

app/views/projects/index.html.erb
<%= render 'shared/projects_listing' , obj: @projects %>

app/views/projects/new.html.erb
<div class=" d-flex flex-column align-items-center my-4">

  <h2>Create new Project</h2>

  <%= form_for @project do |f| %>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class: "form-control my-1" , autofocus: true, placeholder: "Enter Project name" , required: true %>
    </div>

    <div class="form-group">
      <%= f.label :description %><br />
      <%= f.text_field :description , class: "form-control my-1" , autofocus: true, placeholder: "Enter Project description", required: true %>
    </div>

    <div>
      <%= f.label :user_ids, "Developers" %><br />
      <%= f.collection_select :user_ids, User.where(user_type: "developer"), :id , :name , {} , {multiple: true, required: true, class: 'form-control form-control my-1' } %>
    </div>

    <div>
      <%= f.label :user_ids, "QAs" %><br />
      <%= f.collection_select :user_ids, User.where(user_type: "qa"), :id , :name , {} , {multiple: true, required: true, class: 'form-control form-control my-1' } %>
    </div>

    <div class="actions">
      <%= f.submit "Create Project" , class:"my-1 btn btn-primary col-12"%>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="d-flex flex-column align-items-center">
	<h1>
		Project Details
	</h1>
	<div class="col-md-10 my-2">
		<div class="h-100 p-5 text-white bg-dark rounded-3">
		    <h2>Name : <%= @project.name.capitalize %></h2>
		    <h4>Description</h4>
		    <p><%= @project.description %></p>
		    <div>
		    	<h3>Employees working on this project</h3><br>

		    	<% @project.users.each do |u| %>
				<h5><%= u.name.capitalize %> <small><%= u.user_type.capitalize %></small></h4>
					<br>
				<% end %>
		    </div>
		    <div class="d-flex justify-content-center">
		    	<div>
		    		<% if can? :update, @project %>
					<%= link_to "Edit Project" , edit_project_path(@project), class: "btn btn-primary btn-lg" %>
					<% end %>
					<% if can? :destroy, @project  %>
					<%= link_to "Delete Project" , project_path(@project), method: :delete , data: {confirm: "Are you sure?"}, class: "btn btn-primary btn-lg" %>
					<% end %>
					<% if can_create_bug?(@project.id) %>
						<%= link_to "Create Bug" , new_my_bug_path(project_id: @project.id), class: "btn btn-primary btn-lg" %>
					<% end %>
				</div>
		    </div>
		    <br><br>
		    <div class="d-flex justify-content-between">
		    	<div>
		    		<small>Created by: <%= @project.user.name %></small>
		    	</div>
		    	<div>
		    		<small> Created at: <%=  time_ago_in_words(@project.created_at) %></small>
				</div>
		    </div>
		    <% if @project.my_bugs.count > 0 %>
			    <%= render 'shared/bug_listing', bug: @project.my_bugs , title: "Bugs In Project" %>
			<% end %>
		</div>
	</div>
</div>